# Generated by Django 4.1.7 on 2023-04-04 17:37

from django.db import migrations
from django.core.management import call_command


def load_fixture_data(apps, schema_editor):
    call_command("loaddata", "fixture_data.json")


def reverse_load_fixture_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0003_alter_redactor_years_of_experience"),
    ]
    operations = [
        migrations.RunPython(load_fixture_data, reverse_load_fixture_data)
    ]
