# Generated by Django 4.1.7 on 2023-04-06 14:14

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newspaper", "0004_auto_20230404_1737"),
    ]

    operations = [
        migrations.AlterField(
            model_name="redactor",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
